# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1faafadaa0fdf5ba6653560010760e81a4bec76a177f36a3d94be9b91ebf0ffc54d34fa61a58051ba8835701be72ce5a5dda60b1d0809f9097e026e1eb63f3ad

test:
  secret_key_base: 31e3acc11fc3a5cd3cd3f219044158df64aef8e925b12fbdc27f91c8256ffc45e9ff02d4ec99a56dc089aa824c89e48f6786e815549d9d83a4c55cad7583205d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
